# Generated by Django 3.2.12 on 2022-02-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='post_thumbnail',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
