# Generated by Django 3.2.12 on 2022-02-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspaper_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
