# Generated by Django 3.2.12 on 2022-02-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220210_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
