# Generated by Django 3.2.12 on 2022-02-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newspaper_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='excerpt',
            field=models.TextField(max_length=50),
        ),
    ]
