# Generated by Django 3.2.12 on 2022-02-10 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newspaper_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='published',
            field=models.DateField(default=datetime.date(2022, 2, 10)),
        ),
    ]
