# Generated by Django 3.2.12 on 2022-02-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20220213_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='name',
            field=models.CharField(choices=[('The Guardian', 'The Guardian'), ('The Nation', 'The Nation'), ('The Punch', 'The Punch'), ('The Vanguard', 'The Vanguard')], max_length=20),
        ),
    ]
